name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager --install "platforms;android-35" "build-tools;35.0.0" "platform-tools"
          yes | sdkmanager --licenses

      - name: Initialize Gradle wrapper if missing
        run: |
          if [ ! -f gradlew ]; then
            cd app
            gradle wrapper --gradle-version 8.7
            cd ..
          fi

      - name: Generate Gradle Wrapper (project-aware)
        run: |
          ./gradlew wrapper --gradle-version 8.7 || \
          (echo "gradlew not found, initializing..." && gradle wrapper --gradle-version 8.7 --distribution-type bin)
          chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ToggleWidget-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
